version: "3.7"
services:

  Fightplayer:
    environment: 
      - POSTGRES_PASSWORD=mordekai
      - POSTGRES_DB=ufcplayer
      - POSTGRES_USER=marco
    ports: 
      - "5433:5432"
    image: postgres:10-alpine
    volumes: 
      - db-data:/var/lib/postgresql/data

volumes: 
  db-data: